#! /usr/bin/env bash

echoerr() { echo "$@" 1>&2; }

to_pdf='false'
cleanup=''

while getopts ':pc' flag; do
	case "${flag}" in
		p) to_pdf='true' ; shift ;;
		c) cleanup='-c' ; to_pdf='true' ; shift ;;
		*) echoerr "Illegal option: -${OPTARG}"; echoerr "Quitting." ; exit ;;
	esac
done

cwd=$(pwd)
# Change directory to source
cd $(dirname "$(readlink -f "$0")")
python cplexam.py "$1"
cd "$cwd"
if [ $to_pdf = 'true' ]; then
	latexmk -pdf -quiet $cleanup "${1%.*}.tex"
	pwd
	evince "${1%.*}.pdf"
fi
