#! /usr/bin/env bash

echoerr() { echo "$@" 1>&2; }

# options
to_pdf='false'
cleanup='false'

#handle options
while getopts ':pc' flag; do
	case "${flag}" in
		p) to_pdf='true' ; shift ;;
		c) cleanup='true' ; to_pdf='true' ; shift ;;
		*) echoerr "Illegal option: -${OPTARG}"; echoerr "Quitting." ; exit ;;
	esac
done

# check for filename argument
if [ "$1" = '' ]; then
	echoerr "Expected argument filename not found."
	exit
fi

# save current directory
cwd=$(pwd)
# change directory to source
cd "$(dirname "$(readlink -f "$0")")"
# generate tex
if [[ "$1" = /* ]]; then
	# absolute path
	python cplexam.py "$1"
else
	# relative path
	python cplexam.py "$cwd/$1"
fi
# compile pdf from tex
if [ $to_pdf = 'true' ]; then
	cd "$(dirname "$1")"
	latexmk -pdf -quiet "${1%.*}.tex"
	if [ $cleanup = 'true' ]; then
		latexmk -c
	fi
	evince "${1%.*}.pdf"
fi
