#! /usr/bin/env bash

echoerr() { echo "$@" 1>&2; }

# options
to_pdf='false'
cleanup='false'

#handle options
while getopts ':pc' flag; do
	case "${flag}" in
		p) to_pdf='true' ; shift ;;
		c) cleanup='true' ; to_pdf='true' ; shift ;;
		*) echoerr "Illegal option: -${OPTARG}"; echoerr "Quitting." ; exit ;;
	esac
done

# check for filename argument
if [ "$1" = '' ]; then
	echoerr "Expected argument filename not found."
	exit
fi

# save current directory
cwd=$(pwd)
# change directory to source
cd "$(dirname "$(readlink -f "$0")")"
# generate tex
if [[ "$1" = /* ]]; then
	# absolute path
	err=$(python3 examtex.py "$1")
else
	# relative path
	err=$(python3 examtex.py "$cwd/$1")
fi
if [ "$err" != "" ]; then
	echo "$err"
# compile pdf from tex
elif [ $to_pdf = 'true' -a "$err" = "" ]; then
	cd "$(dirname "$1")"
	latexmk -pdf -quiet "${1%.*}-EXAM.tex"
	latexmk -pdf -quiet "${1%.*}-KEY.tex"
	if [ $cleanup = 'true' ]; then
		latexmk -c
	fi
	evince "${1%.*}-EXAM.pdf"
fi
